website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import check_password_hash
from .models import User
from . import db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        login = request.form.get("login")
        password = request.form.get("password")
        remember_me = request.form.get("remember_me")

        user = db.session.scalars(
            db.select(User).where(User.login == login)
        ).one_or_none()
        if user:
            if check_password_hash(user.password_hash, password):
                flash("Успешная авторизация", category="success")
                if remember_me is None:
                    login_user(user)
                else:
                    login_user(user, remember=True)
                return redirect(url_for("views.home_page"))
            else:
                flash(
                    "Невозможно аутентифицироваться с указанными логином и паролем",
                    category="error",
                )
        else:
            flash(
                "Невозможно аутентифицироваться с указанными логином и паролем",
                category="error",
            )

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home_page"))

website/views.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
    current_app,
    jsonify,
)
from flask_login import login_required, logout_user, current_user
from werkzeug.utils import secure_filename
from .models import Book, Style, Cover, Review
import os, hashlib, markdown, bleach
from . import decorators
from . import db

views = Blueprint("views", __name__)

ALLOWED_EXTENSIONS = set(["png", "jpg", "jpeg"])


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def commit_book_data(request, id=None):
    title = request.form.get("title")
    style = request.form.getlist("style")
    short_description = bleach.clean(request.form.get("short_description"))
    year = request.form.get("year")
    publisher = request.form.get("publisher")
    author = request.form.get("author")
    pages = request.form.get("pages")

    if not all(
        [
            title,
            style,
            year,
            publisher,
            author,
            pages,
            short_description != "Краткое описание",
        ]
    ):
        flash("Пожалуйста, введите все данные", category="error")
        return redirect(request.url)

    if "file" in request.files:
        file = request.files["file"]
        if file.filename == "":
            flash("Пожалуйста, введите все данные", category="error")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            file_md5 = hashlib.md5(file.read()).hexdigest()
            filename = secure_filename(file.filename)
            try:
                cover = db.session.scalars(
                    db.select(Cover).where(Cover.MD5_hash == file_md5)
                ).one_or_none()
                if cover:
                    cover_id = cover.id
                else:
                    new_cover = Cover(
                        file_name=filename,
                        MIME_type=file.content_type,
                        MD5_hash=file_md5,
                    )
                    db.session.add(new_cover)
                    db.session.flush()
                    cover_id = new_cover.id
                new_book = Book(
                    title=title,
                    short_description=short_description,
                    year=year,
                    publisher=publisher,
                    author=author,
                    pages=pages,
                    cover_id=cover_id,
                )
                styles = db.session.scalars(
                    db.select(Style).where(Style.id.in_(style))
                ).all()
                new_book.styles.extend(styles)
                db.session.add(new_book)
                db.session.commit()
                book_id = new_book.id
                file.seek(0)
                file.save(os.path.join(current_app.config["UPLOAD_FOLDER"], filename))

                return redirect(url_for("views.view_book", id=book_id))
            except Exception as e:
                db.session.rollback()
                flash(
                    "При сохранении данных возникла ошибка. Проверьте корректность введённых данных.",
                    category="error",
                )
                return redirect(request.url)
    else:
        book = Book.query.get_or_404(id)
        book.title = request.form.get("title")
        book.style = request.form.getlist("style")
        book.short_description = bleach.clean(request.form.get("short_description"))
        book.year = request.form.get("year")
        book.publisher = request.form.get("publisher")
        book.author = request.form.get("author")
        book.pages = request.form.get("pages")
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash(
                "При сохранении данных возникла ошибка. Проверьте корректность введённых данных.",
                category="error",
            )
            return redirect(request.url)


@views.route("/")
def home_page():
    books = Book.query.order_by(Book.year.desc())

    page = request.args.get("page")

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = books.paginate(page=page, per_page=10)

    return render_template("home.html", user=current_user, pages=pages)


@views.route("/add_book", methods=["GET", "POST"])
@decorators.role_required("admin")
def add_book():
    if request.method == "POST":
        return commit_book_data(request)

    styles = db.session.scalars(db.select(Style)).all()

    return render_template("add_book.html", user=current_user, book=None, styles=styles)


@views.route("/view_book/<int:id>", methods=["GET", "POST"])
@decorators.role_required("admin", "mod", "user")
def view_book(id):
    book = Book.query.get_or_404(id)
    book.short_description = markdown.markdown(book.short_description)

    styles = db.session.scalars(db.select(Style)).all()

    reviews = db.session.scalars(
        db.select(Review).where(Review.book_id == id, Review.status == "accepted")
    ).all()

    user_reviewed = db.session.scalars(
        db.select(Review).where(Review.user_id == current_user.id, Review.book_id == id)
    ).all()

    print(user_reviewed)

    # for review in reviews:
    #     review.text = markdown.markdown(review.text)
    #     if review.user_id == current_user.id:
    #         user_reviewed = True

    return render_template(
        "view_book.html",
        user=current_user,
        book=book,
        styles=styles,
        reviews=reviews,
        user_reviewed=user_reviewed,
    )


@views.route("/edit_book/<id>", methods=["GET", "POST"])
@decorators.role_required("admin", "mod")
def edit_book(id):
    book = Book.query.get_or_404(id)

    if request.method == "POST":
        commit_book_data(request, id)
        return redirect(url_for("views.home_page"))
    else:
        styles = db.session.scalars(db.select(Style)).all()
        return render_template(
            "edit_book.html", user=current_user, book=book, styles=styles
        )


@views.route("/delete_book/<id>", methods=["GET", "POST"])
@decorators.role_required("admin")
def delete_book(id):
    book = Book.query.get_or_404(id)

    try:
        cover = book.cover
        cover_count = db.session.scalars(
            db.select(Book).where(cover.id == Book.cover_id)
        ).all()
        db.session.delete(book)
        if cover and len(cover_count) == 1:
            file_path = os.path.join(
                current_app.config["UPLOAD_FOLDER"], cover.file_name
            )
            if os.path.exists(file_path):
                os.remove(file_path)
            db.session.delete(cover)

        db.session.commit()

    except Exception as e:
        db.session.rollback()
        flash(f"Error occured: {e}", category="error")

    return redirect(url_for("views.home_page"))


@views.route("/add_review/<id>", methods=["GET", "POST"])
@decorators.role_required("admin", "mod", "user")
def add_review(id):
    book = Book.query.get_or_404(id)

    reviews = db.session.scalars(db.select(Review).where(Review.book_id == id)).all()

    for review in reviews:
        if review.user_id == current_user.id:
            flash("Вы уже оставляли отзыв", category="error")
            return redirect(url_for("views.home_page"))

    if request.method == "POST":
        book_id = id
        user_id = current_user.id
        score = request.form.get("score")
        text = bleach.clean(request.form.get("text"))

        if text == "Напишите свой отзыв":
            flash("Пожалуйста, введите все данные", category="error")
            return redirect(request.url)

        try:
            new_review = Review(
                book_id=book_id, user_id=user_id, score=score, text=text
            )
            db.session.add(new_review)
            db.session.commit()
            flash(" Успешно! Ваш отзыв на проверке", category="success")
            return redirect(url_for("views.view_book", id=book_id))
        except Exception as e:
            db.session.rollback()
            flash(f"Error occured: {e}", category="error")

    return render_template("add_review.html", user=current_user, book=book)


@views.route("/moderating_reviews", methods=["GET", "POST"])
@decorators.role_required("mod")
def moderating_reviews():
    status = request.args.get("status")
    book_id = request.args.get("book_id")
    user_id = request.args.get("user_id")

    if status and book_id and user_id:

        moderated_review = db.session.scalars(
            db.select(Review).where(
                Review.book_id == book_id, Review.user_id == user_id
            )
        ).one_or_none()

        if status == "declined":
            db.session.delete(moderated_review)
        else:
            moderated_review.status = status

        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash(
                f"{e}",
                category="error",
            )

    reviews = db.session.scalars(
        db.select(Review).where(Review.status == "pending")
    ).all()
    return render_template(
        "moderating_reviews.html", reviews=reviews, user=current_user
    )


@views.route("/my_reviews", methods=["GET"])
@login_required
def my_reviews():
    reviews = db.session.scalars(
        db.select(Review).where(
            Review.user_id == current_user.id, Review.status == "pending"
        )
    ).all()

    return render_template("my_reviews.html", reviews=reviews, user=current_user)

website/templates/add_book.html
{% extends "base.html" %} 
{% block title %}Добавить Книгу{% endblock %}
{% block content %}
{% from 'macros.html' import book_form %}
{{ book_form(book, styles) }}
{% endblock %}

website/templates/add_review.html
{% extends "base.html" %} 
{% block title %}Отзыв{% endblock %}
{% block content %}
<form method="POST">
  <div class="container d-flex flex-column align-items-stretch justify-content-center w-75">
    <h3>Оценка</h3>
    <select class="form-select mb-3" name="score">
      <option selected value="5">Отлично</option>
      <option value="4">Хорошо</option>
      <option value="3">Удовлетворительно</option>
      <option value="2">Неудовлетворительно</option>
      <option value="1">Плохо</option>
      <option value="0">Ужасно</option>
    </select>
    <textarea name="text"></textarea>
    <button type="submit" class="btn btn-primary"> Сохранить </button>
  </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script>
  const reviewMDE = new EasyMDE()
  reviewMDE.value(`Напишите свой отзыв`)
</script>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="ru" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Книгинск{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>
  <body class="bg-dark-subtle">
    <nav class="navbar navbar-expand-lg sticky-top border-bottom bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for("views.home_page") }}">Баденов 221-329</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarToggler">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <span class="navbar-text me-3">
              {{ user.last_name }} {{ user.first_name[0] }}.{{ user.middle_name[0] }}.
            </span>
              {% if user.role.name == "mod" %}
                <a href="{{ url_for("views.moderating_reviews") }}" class="nav-item nav-link" id="moderating_reviews">Отзывы</a>
              {% else %}
                <a href="{{ url_for("views.my_reviews") }}" class="nav-item nav-link" id="my_reviews">Отзывы</a>
              {% endif %}
            <a href="/" class="nav-item nav-link" id="home">Главная</a>
            <a href="{{ url_for("auth.logout") }}" class="nav-item nav-link" id="logout">Выйти</a>
            {% else %}
            <a href="/" class="nav-item nav-link" id="home">Главная</a>
            <a href="{{ url_for("auth.login") }}" class="nav-item nav-link" id="login">Войти</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="d-flex justify-content-center">
            <div class="alert alert-danger alert-dismissible fade show mt-3 w-50" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          </div>
          {% else %}
          <div class="d-flex justify-content-center">
            <div class="alert alert-success alert-dismissible fade show mt-3 w-50" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/card.html
<p>card</p>

website/templates/edit_book.html
{% extends "base.html" %} 
{% block title %}Изменить Книгу{% endblock %}
{% block content %}
{% from 'macros.html' import book_form %}
{{ book_form(book, styles) }}
{% endblock %}

website/templates/home.html
{% extends "base.html" %} 
{% block title %}Книгинск{% endblock %}
{% block content %}
<div class="container">
  <div class="row row-cols-lg-5 row-cols-2">
    {% for book in pages.items %}
      <div class="mt-3 mb-3">
        <div class="card text-center h-100">
          <img src="{{ url_for('static', filename='covers/' + book.cover.file_name) }}" class="card-img-top" alt="{{ book.cover.file_name }}" loading="lazy" style="aspect-ratio:  3/4; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title text-start">{{ book.title }}</h5>
            <p class="card-text text-end">{{ book.author }}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              {% for style in book.styles %}
                  {{ style.style_name }}
              {% endfor %}
            </li>
            <li class="list-group-item">Год издания - {{ book.year }}</li>
            <li class="list-group-item"> 
              {% if book.reviews %}
                Средняя оценка - {{ ((book.reviews | map(attribute='score') | sum) / (book.reviews | length)) | round(2)}}
              {% else %}
                Нет оценок
              {% endif %}
            </li>
            <li class="list-group-item"> Количество рецензий - {{ book.reviews | length }} </li>
          </ul>
          <div class="card-body d-flex justify-content-around align-items-center">
            <a href="{{ url_for('views.view_book', id=book.id) }}" class="btn btn-primary" id="view_book">
              {% if not user.is_authenticated or user.role.name == 'user' %}
                Посмотреть <i class="bi bi-box-arrow-up-right"></i>
              {% else %}
                <i class="bi bi-box-arrow-up-right"></i>
              {% endif %}
            </a>
            {% if user.is_authenticated and user.role.name != 'user' %}
              <a href="{{ url_for('views.edit_book', id=book.id) }}" class="btn btn-success" id="edit_book"><i class="bi bi-pencil-square"></i></a>
            {% endif %}
            {% if user.is_authenticated and user.role.name == 'admin' %}
              <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{ book.id }}"><i class="bi bi-trash"></i></button>
              <div class="modal fade" id="delete{{ book.id }}" tabindex="-1" aria-labelledby="delete{{ book.id }}Label" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="deleteModalLabel">Удаление</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Вы уверены, что хотите удалить книгу {{ book.title }}?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
                      <a href="{{ url_for('views.delete_book', id=book.id) }}" class="btn btn-danger">Да</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
<div class="d-flex justify-content-center mb-3">
	{% if user.is_authenticated and user.role.name == 'admin' %}
	  <a href="{{ url_for('views.add_book') }}" class="btn btn-primary" id="add_book">Добавить книгу</a>
	{% endif %}
</div>
<div class="d-flex justify-content-center">
	<nav aria-label="Page navigation">
		<ul class="pagination">
			<li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
				<a class="page-link" href="?page={{pages.prev_num}}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
				</a>
			</li>
			{% for page in pages.iter_pages() %}
				<li class="page-item">
					<a class="page-link {% if page == pages.page %} active {% endif %}" href="?page={{ page }}">
						{{ page }}
					</a>
				</li>
			{% endfor %}
			<li class="page-item">
				<a class="page-link {% if not pages.has_next %} disabled {% endif %}" href="?page={{pages.next_num}}" aria-label="Next">
					<span aria-hidden="true">&raquo;</span>
				</a>
			</li>
		</ul>
	</nav>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} 
{% block title %}Вход{% endblock %}
{% block content %}
<form method="POST">
  <div class="container d-flex flex-column align-items-center justify-content-center" style="height: 80vh;">
    <div class="form-floating my-2 w-75">
      <input type="text" class="form-control" id="login" name="login" placeholder="Логин">
      <label for="floatingInput">Логин</label>
    </div>
    <div class="form-floating my-2 w-75">
      <input type="password" class="form-control" id="password" name="password" placeholder="Пароль">
      <label for="floatingPassword">Пароль</label>
    </div>
    <div class="form-check my-2 w-75">
      <input type="checkbox" class="form-check-input" id="remember_me" name="remember_me">
      <label class="form-check-label" for="remember_me">Запомнить меня</label>
    </div>
    <button type="submit" class="btn btn-primary my-2 w-50">Войти</button>
  </div>
</form>
{% endblock %}

website/templates/macros.html
{% macro book_form(book, styles) %}
<form method="POST" enctype="multipart/form-data">
  <div class="container d-flex flex-column align-items-stretch justify-content-center w-75">
    <div class="form-floating my-2">
      <input type="text" class="form-control" id="title" name="title" placeholder="Название книги" value="{{ book.title }}">
      <label for="floatingInput">
          Название
      </label>
    </div>
    <select class="form-select mb-2" multiple aria-label="Multiple select example" name="style">
      {% for style in styles %}
        <option value="{{ style.id }}" {% if style in book.styles %}selected{% endif %}> {{ style.style_name }}</option>
      {% endfor %}
    </select>
    <textarea name="short_description"></textarea>
    <div class="form-floating mb-2">
      <input type="number" class="form-control" id="year" name="year" placeholder="Год выпуска" required min="1" max="9999" value="{{ book.year }}">
      <label for="floatingInput">
          Год выпуска
      </label>
    </div>
    <div class="form-floating mb-2">
      <input type="text" class="form-control" id="publisher" name="publisher" placeholder="Издатель" value="{{ book.publisher }}">
      <label for="floatingInput">
          Издатель
      </label>
    </div>
    <div class="form-floating mb-2">
      <input type="text" class="form-control" id="author" name="author" placeholder="Автор" value="{{ book.author }}">
      <label for="floatingInput">
          Автор
      </label>
    </div>
    <div class="form-floating mb-2">
      <input type="number" class="form-control" id="pages" name="pages" placeholder="Количество страниц" required min="1" max="9999" value="{{ book.pages }}">
      <label for="floatingInput">
          Количество страниц
      </label>
    </div>
    {% if not book%}
    <div class="mb-2">
      <label for="formFile" class="form-label">Обложка книги</label>
      <input type="file" class="form-control" id="formFile" name="file">
    </div>
    {% endif %}
    <button type="submit" class="btn btn-primary my-2">Отправить</button>
  </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script>
  const easyMDE = new EasyMDE()
  easyMDE.value(`{{ book.short_description if book.short_description else 'Краткое описание' }}`)
</script>
{% endmacro %}

website/templates/moderating_reviews.html
{% extends "base.html" %}
{% block content %}
  <div class="row row-cols-lg-4 row-cols-2 gap-3 mt-3 justify-content-around">
    {% for review in reviews %}
        <div class="card text-center">
          <h5 class="card-header">
            {{ review.user.last_name }} {{ review.user.first_name[0] }}.{{ review.user.middle_name[0] }}.
          </h5>
          <div class="card-body">
            <h5 class="card-title">Oценка - {{ review.score }}</h5>
            <p class="card-text">{{ review.text.replace('\n', '<br>') | safe }}</p>
              <a href="{{ url_for("views.moderating_reviews", book_id=review.book_id, user_id=review.user_id, status="accepted") }}" class="btn btn-success"><i class="bi bi-check"></i></a>
              <a href="{{ url_for("views.moderating_reviews", book_id=review.book_id, user_id=review.user_id, status="declined") }}" class="btn btn-danger"><i class="bi bi-trash"></i></a>
          </div>
        </div>
    {% endfor %}
  </div>
{% endblock %}

website/templates/my_reviews.html
{% extends "base.html" %}
{% block content %}
  <div class="row row-cols-lg-5 row-cols-2 justify-content-around">
    {% for review in reviews %}
        <div class="card mt-3">
          <h5 class="card-header">
            {{ review.user.last_name }} {{ review.user.first_name[0] }}.{{ review.user.middle_name[0] }}.
          </h5>
          <div class="card-body">
            <h5 class="card-title">Oценка - {{ review.score }}</h5>
            <p class="card-text">{{ review.text.replace('\n', '<br>') | safe }}</p>
            <p>Отзыв на проверке</p>
          </div>
        </div>
    {% endfor %}
  </div>
{% endblock %}

website/templates/view_book.html
{% extends "base.html" %} 
{% block title %}{{ book.title }}{% endblock %}
{% block content %}
<div class="container d-flex flex-column align-items-center mt-3">
  <div class="card mb-3 w-75 h-75">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ url_for('static', filename='covers/' + book.cover.file_name) }}" class="card-img-top" alt="{{ book.cover.file_name }}" loading="lazy">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h1 class="card-title"> {{ book.title }} </h1>
          <h3 class="card-title"> {{ book.author }} </h3>
          <p class="card-text">  {{ book.short_description.replace('\n', '<br>') | safe }} </p>
          <p class="card-text"><strong>Жанр</strong> : {% for style in book.styles %} {{ style.style_name }} {% endfor %}</p>
          <p class="card-text"><strong>Год издания</strong> : {{ book.year }}</p>
          <p class="card-text"><strong>Издатель</strong> : {{ book.publisher }}</p>
          <p class="card-text"><strong>Страниц</strong> : {{ book.pages }}</p>
        </div>
      </div>
    </div>
  </div>
  {% for review in reviews %}
    <div class="card mb-3">
      <h5 class="card-header">
        {{ review.user.last_name }} {{ review.user.first_name[0] }}.{{ review.user.middle_name[0] }}.
      </h5>
      <div class="card-body">
        <h5 class="card-title">Oценка - {{ review.score }}</h5>
        <p class="card-text">{{ review.text.replace('\n', '<br>') | safe }}</p>
      </div>
    </div>
  {% endfor %}
  {% if not user_reviewed %}
    <a href="{{ url_for('views.add_review', id=book.id) }}" class="btn btn-primary mb-3" id="add_review">Написать рецензию <i class="bi bi-pencil-square"></i></a>
  {% endif %}
</div>
{% endblock %}